require('./js/rainbows.js');
require('./js/unicorns.js');
require('./scss/base.scss');
require('./img/sprite.svg');
require('./img/IMG_0079.jpg?sizes[]=40,sizes[]=200,sizes[]=400');
require('./img/logo.png?sizes[]=150');
require('./img/hotel-1.jpg?sizes[]=330,sizes[]=660');
require('./img/hotel-2.jpg?sizes[]=330,sizes[]=660');
require('./img/hotel-3.jpg?sizes[]=330,sizes[]=660');